name: flake8 and coverage

on:
  push

jobs:
  flake8:
    runs-on: ubuntu-latest
    needs: [ coverage ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install flake8

      - name: Lint with flake8
        run: |
          flake8 smrf

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          sudo apt-get install -y libeccodes-tools
          python3 -m pip install --upgrade pip
          python3 -m pip install coverage coveralls PyYAML
          python3 -m pip install -r requirements.txt
          python3 -m pip install .[tests]

      - name: Run coverage
        run: |
          make coveralls
